"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertOneUserResolver = exports.UpdateOneUserResolver = exports.UpdateManyUserResolver = exports.GroupByUserResolver = exports.FindUniqueUserResolver = exports.FindManyUserResolver = exports.FindFirstUserResolver = exports.DeleteOneUserResolver = exports.DeleteManyUserResolver = exports.CreateOneUserResolver = exports.CreateManyUserResolver = exports.AggregateUserResolver = exports.UpsertOneProductResolver = exports.UpdateOneProductResolver = exports.UpdateManyProductResolver = exports.GroupByProductResolver = exports.FindUniqueProductResolver = exports.FindManyProductResolver = exports.FindFirstProductResolver = exports.DeleteOneProductResolver = exports.DeleteManyProductResolver = exports.CreateOneProductResolver = exports.CreateManyProductResolver = exports.AggregateProductResolver = exports.UpsertOneOrderResolver = exports.UpdateOneOrderResolver = exports.UpdateManyOrderResolver = exports.GroupByOrderResolver = exports.FindUniqueOrderResolver = exports.FindManyOrderResolver = exports.FindFirstOrderResolver = exports.DeleteOneOrderResolver = exports.DeleteManyOrderResolver = exports.CreateOneOrderResolver = exports.CreateManyOrderResolver = exports.AggregateOrderResolver = exports.UpsertOneCategoryResolver = exports.UpdateOneCategoryResolver = exports.UpdateManyCategoryResolver = exports.GroupByCategoryResolver = exports.FindUniqueCategoryResolver = exports.FindManyCategoryResolver = exports.FindFirstCategoryResolver = exports.DeleteOneCategoryResolver = exports.DeleteManyCategoryResolver = exports.CreateOneCategoryResolver = exports.CreateManyCategoryResolver = exports.AggregateCategoryResolver = void 0;
var AggregateCategoryResolver_1 = require("./Category/AggregateCategoryResolver");
Object.defineProperty(exports, "AggregateCategoryResolver", { enumerable: true, get: function () { return AggregateCategoryResolver_1.AggregateCategoryResolver; } });
var CreateManyCategoryResolver_1 = require("./Category/CreateManyCategoryResolver");
Object.defineProperty(exports, "CreateManyCategoryResolver", { enumerable: true, get: function () { return CreateManyCategoryResolver_1.CreateManyCategoryResolver; } });
var CreateOneCategoryResolver_1 = require("./Category/CreateOneCategoryResolver");
Object.defineProperty(exports, "CreateOneCategoryResolver", { enumerable: true, get: function () { return CreateOneCategoryResolver_1.CreateOneCategoryResolver; } });
var DeleteManyCategoryResolver_1 = require("./Category/DeleteManyCategoryResolver");
Object.defineProperty(exports, "DeleteManyCategoryResolver", { enumerable: true, get: function () { return DeleteManyCategoryResolver_1.DeleteManyCategoryResolver; } });
var DeleteOneCategoryResolver_1 = require("./Category/DeleteOneCategoryResolver");
Object.defineProperty(exports, "DeleteOneCategoryResolver", { enumerable: true, get: function () { return DeleteOneCategoryResolver_1.DeleteOneCategoryResolver; } });
var FindFirstCategoryResolver_1 = require("./Category/FindFirstCategoryResolver");
Object.defineProperty(exports, "FindFirstCategoryResolver", { enumerable: true, get: function () { return FindFirstCategoryResolver_1.FindFirstCategoryResolver; } });
var FindManyCategoryResolver_1 = require("./Category/FindManyCategoryResolver");
Object.defineProperty(exports, "FindManyCategoryResolver", { enumerable: true, get: function () { return FindManyCategoryResolver_1.FindManyCategoryResolver; } });
var FindUniqueCategoryResolver_1 = require("./Category/FindUniqueCategoryResolver");
Object.defineProperty(exports, "FindUniqueCategoryResolver", { enumerable: true, get: function () { return FindUniqueCategoryResolver_1.FindUniqueCategoryResolver; } });
var GroupByCategoryResolver_1 = require("./Category/GroupByCategoryResolver");
Object.defineProperty(exports, "GroupByCategoryResolver", { enumerable: true, get: function () { return GroupByCategoryResolver_1.GroupByCategoryResolver; } });
var UpdateManyCategoryResolver_1 = require("./Category/UpdateManyCategoryResolver");
Object.defineProperty(exports, "UpdateManyCategoryResolver", { enumerable: true, get: function () { return UpdateManyCategoryResolver_1.UpdateManyCategoryResolver; } });
var UpdateOneCategoryResolver_1 = require("./Category/UpdateOneCategoryResolver");
Object.defineProperty(exports, "UpdateOneCategoryResolver", { enumerable: true, get: function () { return UpdateOneCategoryResolver_1.UpdateOneCategoryResolver; } });
var UpsertOneCategoryResolver_1 = require("./Category/UpsertOneCategoryResolver");
Object.defineProperty(exports, "UpsertOneCategoryResolver", { enumerable: true, get: function () { return UpsertOneCategoryResolver_1.UpsertOneCategoryResolver; } });
var AggregateOrderResolver_1 = require("./Order/AggregateOrderResolver");
Object.defineProperty(exports, "AggregateOrderResolver", { enumerable: true, get: function () { return AggregateOrderResolver_1.AggregateOrderResolver; } });
var CreateManyOrderResolver_1 = require("./Order/CreateManyOrderResolver");
Object.defineProperty(exports, "CreateManyOrderResolver", { enumerable: true, get: function () { return CreateManyOrderResolver_1.CreateManyOrderResolver; } });
var CreateOneOrderResolver_1 = require("./Order/CreateOneOrderResolver");
Object.defineProperty(exports, "CreateOneOrderResolver", { enumerable: true, get: function () { return CreateOneOrderResolver_1.CreateOneOrderResolver; } });
var DeleteManyOrderResolver_1 = require("./Order/DeleteManyOrderResolver");
Object.defineProperty(exports, "DeleteManyOrderResolver", { enumerable: true, get: function () { return DeleteManyOrderResolver_1.DeleteManyOrderResolver; } });
var DeleteOneOrderResolver_1 = require("./Order/DeleteOneOrderResolver");
Object.defineProperty(exports, "DeleteOneOrderResolver", { enumerable: true, get: function () { return DeleteOneOrderResolver_1.DeleteOneOrderResolver; } });
var FindFirstOrderResolver_1 = require("./Order/FindFirstOrderResolver");
Object.defineProperty(exports, "FindFirstOrderResolver", { enumerable: true, get: function () { return FindFirstOrderResolver_1.FindFirstOrderResolver; } });
var FindManyOrderResolver_1 = require("./Order/FindManyOrderResolver");
Object.defineProperty(exports, "FindManyOrderResolver", { enumerable: true, get: function () { return FindManyOrderResolver_1.FindManyOrderResolver; } });
var FindUniqueOrderResolver_1 = require("./Order/FindUniqueOrderResolver");
Object.defineProperty(exports, "FindUniqueOrderResolver", { enumerable: true, get: function () { return FindUniqueOrderResolver_1.FindUniqueOrderResolver; } });
var GroupByOrderResolver_1 = require("./Order/GroupByOrderResolver");
Object.defineProperty(exports, "GroupByOrderResolver", { enumerable: true, get: function () { return GroupByOrderResolver_1.GroupByOrderResolver; } });
var UpdateManyOrderResolver_1 = require("./Order/UpdateManyOrderResolver");
Object.defineProperty(exports, "UpdateManyOrderResolver", { enumerable: true, get: function () { return UpdateManyOrderResolver_1.UpdateManyOrderResolver; } });
var UpdateOneOrderResolver_1 = require("./Order/UpdateOneOrderResolver");
Object.defineProperty(exports, "UpdateOneOrderResolver", { enumerable: true, get: function () { return UpdateOneOrderResolver_1.UpdateOneOrderResolver; } });
var UpsertOneOrderResolver_1 = require("./Order/UpsertOneOrderResolver");
Object.defineProperty(exports, "UpsertOneOrderResolver", { enumerable: true, get: function () { return UpsertOneOrderResolver_1.UpsertOneOrderResolver; } });
var AggregateProductResolver_1 = require("./Product/AggregateProductResolver");
Object.defineProperty(exports, "AggregateProductResolver", { enumerable: true, get: function () { return AggregateProductResolver_1.AggregateProductResolver; } });
var CreateManyProductResolver_1 = require("./Product/CreateManyProductResolver");
Object.defineProperty(exports, "CreateManyProductResolver", { enumerable: true, get: function () { return CreateManyProductResolver_1.CreateManyProductResolver; } });
var CreateOneProductResolver_1 = require("./Product/CreateOneProductResolver");
Object.defineProperty(exports, "CreateOneProductResolver", { enumerable: true, get: function () { return CreateOneProductResolver_1.CreateOneProductResolver; } });
var DeleteManyProductResolver_1 = require("./Product/DeleteManyProductResolver");
Object.defineProperty(exports, "DeleteManyProductResolver", { enumerable: true, get: function () { return DeleteManyProductResolver_1.DeleteManyProductResolver; } });
var DeleteOneProductResolver_1 = require("./Product/DeleteOneProductResolver");
Object.defineProperty(exports, "DeleteOneProductResolver", { enumerable: true, get: function () { return DeleteOneProductResolver_1.DeleteOneProductResolver; } });
var FindFirstProductResolver_1 = require("./Product/FindFirstProductResolver");
Object.defineProperty(exports, "FindFirstProductResolver", { enumerable: true, get: function () { return FindFirstProductResolver_1.FindFirstProductResolver; } });
var FindManyProductResolver_1 = require("./Product/FindManyProductResolver");
Object.defineProperty(exports, "FindManyProductResolver", { enumerable: true, get: function () { return FindManyProductResolver_1.FindManyProductResolver; } });
var FindUniqueProductResolver_1 = require("./Product/FindUniqueProductResolver");
Object.defineProperty(exports, "FindUniqueProductResolver", { enumerable: true, get: function () { return FindUniqueProductResolver_1.FindUniqueProductResolver; } });
var GroupByProductResolver_1 = require("./Product/GroupByProductResolver");
Object.defineProperty(exports, "GroupByProductResolver", { enumerable: true, get: function () { return GroupByProductResolver_1.GroupByProductResolver; } });
var UpdateManyProductResolver_1 = require("./Product/UpdateManyProductResolver");
Object.defineProperty(exports, "UpdateManyProductResolver", { enumerable: true, get: function () { return UpdateManyProductResolver_1.UpdateManyProductResolver; } });
var UpdateOneProductResolver_1 = require("./Product/UpdateOneProductResolver");
Object.defineProperty(exports, "UpdateOneProductResolver", { enumerable: true, get: function () { return UpdateOneProductResolver_1.UpdateOneProductResolver; } });
var UpsertOneProductResolver_1 = require("./Product/UpsertOneProductResolver");
Object.defineProperty(exports, "UpsertOneProductResolver", { enumerable: true, get: function () { return UpsertOneProductResolver_1.UpsertOneProductResolver; } });
var AggregateUserResolver_1 = require("./User/AggregateUserResolver");
Object.defineProperty(exports, "AggregateUserResolver", { enumerable: true, get: function () { return AggregateUserResolver_1.AggregateUserResolver; } });
var CreateManyUserResolver_1 = require("./User/CreateManyUserResolver");
Object.defineProperty(exports, "CreateManyUserResolver", { enumerable: true, get: function () { return CreateManyUserResolver_1.CreateManyUserResolver; } });
var CreateOneUserResolver_1 = require("./User/CreateOneUserResolver");
Object.defineProperty(exports, "CreateOneUserResolver", { enumerable: true, get: function () { return CreateOneUserResolver_1.CreateOneUserResolver; } });
var DeleteManyUserResolver_1 = require("./User/DeleteManyUserResolver");
Object.defineProperty(exports, "DeleteManyUserResolver", { enumerable: true, get: function () { return DeleteManyUserResolver_1.DeleteManyUserResolver; } });
var DeleteOneUserResolver_1 = require("./User/DeleteOneUserResolver");
Object.defineProperty(exports, "DeleteOneUserResolver", { enumerable: true, get: function () { return DeleteOneUserResolver_1.DeleteOneUserResolver; } });
var FindFirstUserResolver_1 = require("./User/FindFirstUserResolver");
Object.defineProperty(exports, "FindFirstUserResolver", { enumerable: true, get: function () { return FindFirstUserResolver_1.FindFirstUserResolver; } });
var FindManyUserResolver_1 = require("./User/FindManyUserResolver");
Object.defineProperty(exports, "FindManyUserResolver", { enumerable: true, get: function () { return FindManyUserResolver_1.FindManyUserResolver; } });
var FindUniqueUserResolver_1 = require("./User/FindUniqueUserResolver");
Object.defineProperty(exports, "FindUniqueUserResolver", { enumerable: true, get: function () { return FindUniqueUserResolver_1.FindUniqueUserResolver; } });
var GroupByUserResolver_1 = require("./User/GroupByUserResolver");
Object.defineProperty(exports, "GroupByUserResolver", { enumerable: true, get: function () { return GroupByUserResolver_1.GroupByUserResolver; } });
var UpdateManyUserResolver_1 = require("./User/UpdateManyUserResolver");
Object.defineProperty(exports, "UpdateManyUserResolver", { enumerable: true, get: function () { return UpdateManyUserResolver_1.UpdateManyUserResolver; } });
var UpdateOneUserResolver_1 = require("./User/UpdateOneUserResolver");
Object.defineProperty(exports, "UpdateOneUserResolver", { enumerable: true, get: function () { return UpdateOneUserResolver_1.UpdateOneUserResolver; } });
var UpsertOneUserResolver_1 = require("./User/UpsertOneUserResolver");
Object.defineProperty(exports, "UpsertOneUserResolver", { enumerable: true, get: function () { return UpsertOneUserResolver_1.UpsertOneUserResolver; } });
