"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertOneProductArgs = exports.UpdateOneProductArgs = exports.UpdateManyProductArgs = exports.GroupByProductArgs = exports.FindUniqueProductArgs = exports.FindManyProductArgs = exports.FindFirstProductArgs = exports.DeleteOneProductArgs = exports.DeleteManyProductArgs = exports.CreateOneProductArgs = exports.CreateManyProductArgs = exports.AggregateProductArgs = void 0;
var AggregateProductArgs_1 = require("./AggregateProductArgs");
Object.defineProperty(exports, "AggregateProductArgs", { enumerable: true, get: function () { return AggregateProductArgs_1.AggregateProductArgs; } });
var CreateManyProductArgs_1 = require("./CreateManyProductArgs");
Object.defineProperty(exports, "CreateManyProductArgs", { enumerable: true, get: function () { return CreateManyProductArgs_1.CreateManyProductArgs; } });
var CreateOneProductArgs_1 = require("./CreateOneProductArgs");
Object.defineProperty(exports, "CreateOneProductArgs", { enumerable: true, get: function () { return CreateOneProductArgs_1.CreateOneProductArgs; } });
var DeleteManyProductArgs_1 = require("./DeleteManyProductArgs");
Object.defineProperty(exports, "DeleteManyProductArgs", { enumerable: true, get: function () { return DeleteManyProductArgs_1.DeleteManyProductArgs; } });
var DeleteOneProductArgs_1 = require("./DeleteOneProductArgs");
Object.defineProperty(exports, "DeleteOneProductArgs", { enumerable: true, get: function () { return DeleteOneProductArgs_1.DeleteOneProductArgs; } });
var FindFirstProductArgs_1 = require("./FindFirstProductArgs");
Object.defineProperty(exports, "FindFirstProductArgs", { enumerable: true, get: function () { return FindFirstProductArgs_1.FindFirstProductArgs; } });
var FindManyProductArgs_1 = require("./FindManyProductArgs");
Object.defineProperty(exports, "FindManyProductArgs", { enumerable: true, get: function () { return FindManyProductArgs_1.FindManyProductArgs; } });
var FindUniqueProductArgs_1 = require("./FindUniqueProductArgs");
Object.defineProperty(exports, "FindUniqueProductArgs", { enumerable: true, get: function () { return FindUniqueProductArgs_1.FindUniqueProductArgs; } });
var GroupByProductArgs_1 = require("./GroupByProductArgs");
Object.defineProperty(exports, "GroupByProductArgs", { enumerable: true, get: function () { return GroupByProductArgs_1.GroupByProductArgs; } });
var UpdateManyProductArgs_1 = require("./UpdateManyProductArgs");
Object.defineProperty(exports, "UpdateManyProductArgs", { enumerable: true, get: function () { return UpdateManyProductArgs_1.UpdateManyProductArgs; } });
var UpdateOneProductArgs_1 = require("./UpdateOneProductArgs");
Object.defineProperty(exports, "UpdateOneProductArgs", { enumerable: true, get: function () { return UpdateOneProductArgs_1.UpdateOneProductArgs; } });
var UpsertOneProductArgs_1 = require("./UpsertOneProductArgs");
Object.defineProperty(exports, "UpsertOneProductArgs", { enumerable: true, get: function () { return UpsertOneProductArgs_1.UpsertOneProductArgs; } });
