"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertOneOrderArgs = exports.UpdateOneOrderArgs = exports.UpdateManyOrderArgs = exports.GroupByOrderArgs = exports.FindUniqueOrderArgs = exports.FindManyOrderArgs = exports.FindFirstOrderArgs = exports.DeleteOneOrderArgs = exports.DeleteManyOrderArgs = exports.CreateOneOrderArgs = exports.CreateManyOrderArgs = exports.AggregateOrderArgs = void 0;
var AggregateOrderArgs_1 = require("./AggregateOrderArgs");
Object.defineProperty(exports, "AggregateOrderArgs", { enumerable: true, get: function () { return AggregateOrderArgs_1.AggregateOrderArgs; } });
var CreateManyOrderArgs_1 = require("./CreateManyOrderArgs");
Object.defineProperty(exports, "CreateManyOrderArgs", { enumerable: true, get: function () { return CreateManyOrderArgs_1.CreateManyOrderArgs; } });
var CreateOneOrderArgs_1 = require("./CreateOneOrderArgs");
Object.defineProperty(exports, "CreateOneOrderArgs", { enumerable: true, get: function () { return CreateOneOrderArgs_1.CreateOneOrderArgs; } });
var DeleteManyOrderArgs_1 = require("./DeleteManyOrderArgs");
Object.defineProperty(exports, "DeleteManyOrderArgs", { enumerable: true, get: function () { return DeleteManyOrderArgs_1.DeleteManyOrderArgs; } });
var DeleteOneOrderArgs_1 = require("./DeleteOneOrderArgs");
Object.defineProperty(exports, "DeleteOneOrderArgs", { enumerable: true, get: function () { return DeleteOneOrderArgs_1.DeleteOneOrderArgs; } });
var FindFirstOrderArgs_1 = require("./FindFirstOrderArgs");
Object.defineProperty(exports, "FindFirstOrderArgs", { enumerable: true, get: function () { return FindFirstOrderArgs_1.FindFirstOrderArgs; } });
var FindManyOrderArgs_1 = require("./FindManyOrderArgs");
Object.defineProperty(exports, "FindManyOrderArgs", { enumerable: true, get: function () { return FindManyOrderArgs_1.FindManyOrderArgs; } });
var FindUniqueOrderArgs_1 = require("./FindUniqueOrderArgs");
Object.defineProperty(exports, "FindUniqueOrderArgs", { enumerable: true, get: function () { return FindUniqueOrderArgs_1.FindUniqueOrderArgs; } });
var GroupByOrderArgs_1 = require("./GroupByOrderArgs");
Object.defineProperty(exports, "GroupByOrderArgs", { enumerable: true, get: function () { return GroupByOrderArgs_1.GroupByOrderArgs; } });
var UpdateManyOrderArgs_1 = require("./UpdateManyOrderArgs");
Object.defineProperty(exports, "UpdateManyOrderArgs", { enumerable: true, get: function () { return UpdateManyOrderArgs_1.UpdateManyOrderArgs; } });
var UpdateOneOrderArgs_1 = require("./UpdateOneOrderArgs");
Object.defineProperty(exports, "UpdateOneOrderArgs", { enumerable: true, get: function () { return UpdateOneOrderArgs_1.UpdateOneOrderArgs; } });
var UpsertOneOrderArgs_1 = require("./UpsertOneOrderArgs");
Object.defineProperty(exports, "UpsertOneOrderArgs", { enumerable: true, get: function () { return UpsertOneOrderArgs_1.UpsertOneOrderArgs; } });
